- id: '1651374432871'
  alias: Notification on change in /config folder
  description: ''
  trigger:
  - platform: event
    event_type: folder_watcher
    event_data:
      event_type: created
  - platform: event
    event_type: folder_watcher
    event_data:
      event_type: deleted
  - platform: event
    event_type: folder_watcher
    event_data:
      event_type: modified
  - platform: event
    event_type: folder_watcher
    event_data:
      event_type: moved
  condition: []
  action:
  - service: shell_command.push_to_github
    data: {}
  mode: single
- id: '1651622520272'
  alias: Lovelace dashboard changed
  description: ''
  trigger:
  - platform: event
    event_type: lovelace_updated
  condition: []
  action:
  - service: shell_command.push_to_github
    data: {}
  mode: single
- id: '1689132683051'
  alias: hasip
  description: ''
  trigger:
  - platform: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: vsZJKSeRNc0Ttm1ayNigmXbA
  condition: []
  action:
  - if:
    - condition: template
      value_template: '{{trigger.json.menu_id == ''quit''}}'
    then:
    - service: persistent_notification.create
      data:
        message: pressed 9. quit.
    else:
    - if:
      - condition: template
        value_template: '{{trigger.json.menu_id == ''light_on''}}'
      then:
      - service: persistent_notification.create
        data:
          message: Pressed 1. Light ON.
      else:
      - if:
        - condition: template
          value_template: '{{trigger.json.menu_id == ''light_off''}}'
        then:
        - service: persistent_notification.create
          data:
            message: Pressed 2. Light OFF.
  mode: single
- id: '1689390192597'
  alias: hasip2
  description: ''
  trigger:
  - platform: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: sip_call_webhook_id
  condition:
  - condition: template
    value_template: '{{ trigger.json.sip_account == 2 }}'
  action:
  - service: hassio.addon_stdin
    data_template:
      addon: c7744bff_ha-sip
      input:
        command: answer
        number: '1'
        menu:
          message: Please enter your access code
          choices_are_pin: true
          choices:
            '1234':
              id: owner
              message: Welcome beautiful.
              post_action: hangup
            '5432':
              id: maintenance
              message: Your entrance has been logged.
              post_action: hangup
            '5678':
              id: download
              message: '{{ states.sensor.download_speed.state }}'
              post_action: return
            default:
              id: wrong_code
              message: Wrong code, please try again
              post_action: return
  mode: single
