
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  allowlist_external_dirs:
    - "/config"
  customize:
    sensor.solar_e_today:
      state_class: "total_increasing"
      last_reset: "{{ now().strftime('%Y-%m-%d 00:00:00+11:00') }}"
  packages: !include_dir_merge_named packages/

sensor: !include_dir_merge_list sensors/

  
