
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  allowlist_external_dirs:
    - "/config"
  customize:
    sensor.solar_e_today:
      state_class: "total_increasing"
      last_reset: "{{ now().strftime('%Y-%m-%d 00:00:00+11:00') }}"

sensor:
# ZeverSolar Inverter Local Data Sensors
  - platform: rest
    name: Solar Error #0 When No Error
    resource: http://192.168.81.157/home.cgi
    value_template: "{{ value.split()[8].split()[0] }}" 
  - platform: rest
    name: Solar Pac
    unit_of_measurement: W
    resource: http://192.168.81.157/home.cgi
    value_template: "{{ value.split()[11].split()[0] }}"
    device_class: "power"
  - platform: rest
    name: Solar E_Today
    unit_of_measurement: kWh  
    resource: http://192.168.81.157/home.cgi
    value_template: "{{ value.split()[12].split()[0] }}"
    device_class: "energy"
  - platform: rest
    name: Solar Status #OK When No Error
    resource: http://192.168.81.157/home.cgi
    value_template: "{{ value.split()[13].split()[0] }}" 
    
folder_watcher:
  - folder: /config
    patterns:
      - '*.yaml'
      - '*.yml'
      - '*.txt'
      - '*.md'
      - '*.cpp'
      - '*.h'
      - '*.c'
      - '*.js'
      - '*.html'
      - '*.css'
      - '*.sh'
      
shell_command:
  push_to_github: "./shellscripts/config_folder_changed.sh"
  
  

  

  
  

  

  

      
      
    
    
  