esphome:
  name: co2sensor

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0
  
# Enable Home Assistant API
api:
  #encryption:
  #  key: "nWow3LN9g6M4ArhwoAabANpZihb8l/vDeU9pgf4o/aU="
  services:
    - service: mhz19_calibrate_zero
      then:
        - mhz19.calibrate_zero: myMHZ19B    

ota:
# password: "f1763d435609873b1828962fae2d37a3"

wifi:
  ssid: MelbPC-NUE
  password: peachspeak38

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Co2Sensor Fallback Hotspot"
    password: "Mo37TuLyCHE6"

captive_portal:


uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: myMHZ19B
    co2:
      name: "MH-Z19 CO2 Value"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 60s
    automatic_baseline_calibration: true
    
    