substitutions:
  name: m5stack-atom-echo-846e30
  friendly_name: M5Stack Atom Echo 846e30
packages:
  m5stack.atom-echo: github://esphome/media-players/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: fHE8dTe9NeqcaScx3BHDR/ZS5VaBjt20v1sklFie5Wk=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
