esphome:
  name: toproomd1mini
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: 600.0
    then:
      - delay: 1s
      - output.turn_on: gpio_red

wifi:
  ssid: "MelbPC-NUE"
  password: "peachspeak38"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "toproomd1mini"

logger:
   
web_server:

api:

ota:

output:
  - platform: gpio
    pin: D5
    id: gpio_red
  - platform: gpio
    pin: D6
    id: gpio_yellow
  - platform: gpio
    pin: D7
    id: gpio_green

